version: '3.3'

services:
    db:
        container_name: wp_db
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 5puHctQ9H3RxNwz72nQY
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        container_name: wp_web
        depends_on:
            - db
        image: iohnatan/wordpress-xdebug-wpcli:latest
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

            # WordPress setup variables
            WP_URL: http://localhost:8000
            WP_TITLE: Dev-Site # no spaces
            WP_ADMIN_USER: admin
            WP_ADMIN_PASSWORD: PRQSyZFGq4p3CSNbx3Xw
            WP_ADMIN_EMAIL: docker-wordpress-xdebug-wpcli@mailinator.com

        # setup wordpress after container start: https://stackoverflow.com/a/41854997
        healthcheck:
            test: /config-wordpress.sh || exit 1
            interval: 5s
            timeout: 6s
            retries: 3

    phpmyadmin:
        container_name: wp_phpmyadmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - "8080:80"

volumes:
    db_data: {}